{
    'name': 'Student Management',
    'version': '18.0.1.0.0',
    'summary': 'A module to manage students',
    'description': 'This module allows you to create, view, and manage student records.',
    'author': 'Yelinko',
    'website': 'https://www.yelinko.com',
    'category': 'Education',
    'depends': ['base', 'board', 'account'],
    'data': [
        'security/ir.model.access.csv',
        'data/student_invoice_sequence.xml',
        'data/student_payment_sequence.xml',
        'views/student_invoice_views.xml',
        'views/student_payment_views.xml',
        'views/account_move_inherit_views.xml',
        'views/course_inherit_views.xml',
        'views/course_registration_wizard_views.xml',
        'views/student_views.xml',
        'views/course_views.xml',
        'views/teacher_views.xml',
        'report/student_report.xml',
        'views/student_dashboard.xml',
    ],
    'demo': [
        'demo/demo.xml',
        'demo/student_management_demo.xml',
    ],
    'installable': True,
    'application': True,
}